trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  - group: Github

steps:
  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  - script: |
      git checkout master || git checkout -b master
      git remote add github https://$(GITHUB_PAT)@github.com/worldbank/FuzzyAI.git
      git push github HEAD:refs/heads/master
    displayName: 'Push to worldbank/FuzzyAI'